### ISSUE TITLE
Determining relative abundance of strains

### ISSUE THREAD

**Issue by smb20200615** [dib-lab/genome-grist#45]
Hello,

My understanding is that genome grist tells us what genomes are present. I am trying to determine the relative abundance of different strains that are found to be present. Can I do this by just using --track-abundance when running sourmash compute to make the database that is used by sourmash gather?

Also, would you mind explaining the difference between hashes classified to this genome, mapped bp to this genome, and hashes classified to this species?

Thank you!

**Comment by ctb** [comment]
> Hello,
> 
> My understanding is that genome grist tells us what genomes are present. I am trying to determine the relative abundance of different strains that are found to be present. Can I do this by just using --track-abundance when running sourmash compute to make the database that is used by sourmash gather?

yes, that should work! although I need to revisit to make sure we're keeping abundances through all the steps.
 
> Also, would you mind explaining the difference between hashes classified to this genome, mapped bp to this genome, and hashes classified to this species?

I will need to revisit, and [you can skim our draft paper here too](https://github.com/dib-lab/2020-paper-sourmash-gather/), but briefly --

* hashes classified to this genome: just that, in the sense that sourmash has classified that many k-mers (as represented by hashes) to this genome sequence, per [the gather algorithm](https://sourmash.readthedocs.io/en/latest/classifying-signatures.html#breaking-down-metagenomic-samples-with-gather-and-lca). Note there's some trickiness to ` f_unique_to_query` vs `f_match_orig`, in that in the former we subtract things that have already been allocated to other genomes in earlier gather ranks.
* mapped bp to this genome: how many bases in the reference genome are covered by minimap2-mapped reads from the metagenome. The tricky bit again is that in this case it's _after_ reads have been subtracted if they map to earlier genomes in the gather rank (although genome-grist reports both numbers, analogously to the ` f_unique_to_query` and `f_match_orig` above).
* "hashes classified to this species" - I've not been good about consistent terminology here, but this probably means the mapping equivalent to `f_match_orig`.
* (I also have some prototype notebooks where I literally pull matches back to the species level as measured by NCBI taxonomy, but I don't think that's what you're referring to).

apologies for all the confusion, documentation in early days. please keep asking questions!

**Comment by smb20200615** [comment]
Thank you so much for your thorough explanations and references. It explains a lot. I get zeros for median and average abundance so maybe I will try making this a separate step after genome-grist.

**Comment by ctb** [comment]
zeros for median and average... hmm, maybe what's going on is that it's taking the median across the entire genome, rather than the median for the matched hashes... that could be adjusted. please leave this issue open and I'll do some digging!

**Comment by smb20200615** [comment]
Apologies for bothering you again Dr. Brown. I was just wondering, do you know when this feature would be added? I am very interested in testing your tool on a mock data set and using it on subsequent analyses and this relative abundance of strains is the main feature that I am interested in. Thank you again for your tool. Worked beautifully in reliably detecting the actual presence of the strains in mock.

**Comment by ctb** [comment]
hi @smb20200615 thanks for asking! just to confirm you're speaking about the zeros? I'll see what I can do :).

**Comment by smb20200615** [comment]
Yes, sir. Thank you again so much for your wonderful tool. As in how do we determine the actual relative abundance of the isolates once they have been found to be present in the sample. Right now, I just get zeros.

**Comment by ctb** [comment]
You are very welcome, it's wonderful to hear that people are finding the tool (potentially) useful!

so, I looked at the code.

* [intersect_mins is calculated from the intersection of the remaining query & the match](https://github.com/dib-lab/sourmash/blob/128e50c1b417cd47f897b51843b780987e30a389/src/sourmash/search.py#L164)
* [intersect_abunds is calculated from the abundances in the original signature for the hashes in intersect_mins](https://github.com/dib-lab/sourmash/blob/128e50c1b417cd47f897b51843b780987e30a389/src/sourmash/search.py#L191)
* [average_abund and median_abund and std_abund are calculated from intersect_abunds](https://github.com/dib-lab/sourmash/blob/128e50c1b417cd47f897b51843b780987e30a389/src/sourmash/search.py#L194)

and the only way they _should_ be zero is if track_abundance isn't set, i.e. if there are no abundances in the query signature.

So, apologies for double checking, but - are you creating the signatures with --track-abundance?

(I think the output is confusing regardless, and will look into changing it so that the values are either None or -1 if track_abundance isn't set.)

**Comment by ctb** [comment]
note: #1328 changes things so those columns are empty, rather than 0, if abundances are not used.

**Comment by smb20200615** [comment]
Yes, I am using the --track-abundance option but had to alter your workflow to use it on some isolate genomes. Could that be the issue? I will rebuild the signatures to see whether that resolves things.  Maybe I missed something the first time.

**Comment by ctb** [comment]
On Mon, Feb 15, 2021 at 09:11:29AM -0800, smb20200615 wrote:
> Yes, I am using the --track-abundance option but had to alter your workflow to use it on some isolate genomes. Could that be the issue? I will rebuild the signatures to see whether that resolves things.  Maybe I missed something the first time.

no worries - let me know!

note that you can use 'sourmash sig describe' to confirm that your signatures
have track_abundance set; you would see track_abundance=1 in the output
(instead of track_abundance=0).

looking at the code, the behavior you're seeing is definitely a bug, and I'm
eager to resolve it!

**Comment by smb20200615** [comment]
I just rebuilt the signatures and get track_abundance=1 but still the outputs/genbank/*.x.genbank.gather.csv have all zeroes for abundance columns.

**Comment by smb20200615** [comment]
I am using an older version of genome-grist maybe I will clone again. And a bit off topic but is genome-grist capable of inferring relative abundance from the unique kmers?

**Comment by ctb** [comment]
that code's been in sourmash for a while so updating genome-grist shouldn't change anything. hmm...

oh. 🤦 I see the problem. fix incoming. my sincere apologies. 

and I looked into the relative abundance stuff a little bit a while back. it seemed to be too highly variable to be useful, but I'm happy to point out at the relevant output fields! let me just fix the other thing first :)

**Comment by ctb** [comment]
OK, the abundance calculations in genome-grist should be fixed in https://github.com/dib-lab/genome-grist/pull/64. I don't know if you have the ability to work with unmerged branches or unreleased versions; if you do, please give it a try :).

**Comment by ctb** [comment]
I've released genome-grist 0.7 - it should fix this issue! please let me know if it doesn't...

**Comment by smb20200615** [comment]
Thank you so much for your help. It just finished running for me and I am still getting zeroes. I will now try genome-grist 0.7.

**Comment by ctb** [comment]
On Mon, Feb 15, 2021 at 04:18:44PM -0800, smb20200615 wrote:
> Thank you so much for your help. It just finished running for me and I am still getting zeroes. I will now try genome-grist 0.7. 

excellent, please let me know!

**Comment by ctb** [comment]
closing for now.
